[package]
name = "dubit/simple-store"
version = "1.1.0"
realm = "server"
registry = "https://github.com/upliftgames/wally-index"
license = "MIT"

description = "A simple DubitStore wrapper."

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
DubitStore = "dubit/dubit-store@1.x.x"
Sift = "csqrl/sift@0.x.x"
Signal = "sleitnick/signal@1.x.x"