[tools]
selene = "Kampfkarren/selene@0.27.1"
wally = "UpliftGames/wally@0.3.2"
rojo = "rojo-rbx/rojo@7.4.1"
lune = "filiptibell/lune@0.7.9"
stylua = "JohnnyMorganz/StyLua@2.0.2"
moonwave = "evaera/moonwave@1.1.2"
