# MoonWave configuration file, this file was copied from the following default config:
#		https://eryn.io/moonwave/docs/Configuration/
#		https://github.com/evaera/moonwave/blob/deca62aaa340f189050fb270de2e603199f911a5/cli/src/prepareProject.ts#L39

gitRepoUrl = "https://github.com/dubit/roblox-dubit-tools"
gitSourceBranch = "main"

title = "Roblox Dubit Tools"
changelog = false

autoSectionPath = "Packages"

# Docusaurus settings
[docusaurus]
onBrokenLinks = "warn"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.ico"

organizationName = "Dubit"
projectName = "Roblox Dubit Tools"
baseUrl = "/"

tagline = "Dubit tools for the Roblox platform"
title = "Roblox Dubit Tools"

[navbar]
title = "Roblox Dubit Tools"

[navbar.logo]
src = "https://avatars.githubusercontent.com/u/16320783?s=200&v=4"

# Home Settings
[home]
enabled = true
includeReadme = false
bannerImage = "https://assets.website-files.com/62a30c2a36b1ddc56cc269e4/6454cc297ae02d9dd2088d25_nct-hero.webp"

[[home.features]]
title = "Dubit Store"
description = "DubitStore is a Roblox DataStore library"

[[home.features]]
title = "Allocation Pool"
description = "A simple library designed to consume global budgets"

[[home.features]]
title = "Event Tracker"
description = "A library designed to simply add events into roblox experiences"

[[home.features]]
title = "Dubit Chassis"
description = "DubitChassis is a Raycast Suspension Physics Component system."

# Docusaurus footer
[footer]
style = "dark"
copyright = "Copyright © 2023 Dubit. Built with Moonwave and Docusaurus"