[package]
name = "dubit/engagements"
version = "0.0.1-dev.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
licence = ""
authors = []

description = "package that enables developers to easily query and handle events, objects, interfaces engagements from within a Roblox experience."

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.lock", "wally.toml"]

[dev-dependencies]
TestEz = "roblox/testez@0.4.1"

[dependencies]
Signal = "sleitnick/signal@2.0.3"