local Players = game:GetService("Players")
local LogService = game:GetService("LogService")

local DebugToolRootPath = script.Parent
local SharedRootPath = DebugToolRootPath.Parent.Shared

local Networking = require(DebugToolRootPath.Networking)

local Signal = require(SharedRootPath.Signal)

type Message = {
	Content: string,
	ContentType: Enum.MessageType,

	Amount: number,
	ServerSide: boolean,

	Timestamp: number,
}

local MAX_MESSAGES = 400

local messageAddedSignal = Signal.new()

local messages: { Message } = {}
local latestMessage: Message?

local function mergeLatestExactMessages()
	local messagesCount = #messages

	if messagesCount < 2 then
		return
	end

	local minusOneMessage = messages[messagesCount - 1]
	local lastMessage = messages[messagesCount]

	local matchingContent = lastMessage.Content == minusOneMessage.Content
	local matchingType = lastMessage.ContentType == minusOneMessage.ContentType

	if matchingType and matchingContent then
		minusOneMessage.Amount += 1

		table.remove(messages, table.find(messages, lastMessage))

		latestMessage = minusOneMessage
	end
end

local parsingMessageStack = false
local function addMessage(text: string, textType: Enum.MessageType, serverSided: boolean, timestamp: number?)
	if latestMessage and textType == Enum.MessageType.MessageInfo then
		if text == "Stack Begin" then
			parsingMessageStack = true

			-- The errors report stack trace as an information not as a part of the error message.
			if latestMessage.ContentType == Enum.MessageType.MessageInfo then
				latestMessage.ContentType = Enum.MessageType.MessageError
			end
			return
		elseif text == "Stack End" then
			parsingMessageStack = false
			return
		elseif parsingMessageStack then
			latestMessage.Content ..= `\n  ╠ {text}`
			mergeLatestExactMessages()
			return
		end
	end

	local newMessage: Message = {
		Content = text,
		ContentType = textType,

		Amount = 1,
		ServerSide = serverSided,

		Timestamp = timestamp or os.clock(),
	}

	table.insert(messages, newMessage)

	if #messages > MAX_MESSAGES then
		table.remove(messages, 1)
	end

	latestMessage = newMessage
	mergeLatestExactMessages()

	messageAddedSignal:Fire(text, textType)
end

LogService.MessageOut:Connect(function(message: string, messageType: Enum.MessageType)
	addMessage(message, messageType, false)
end)
for _, messageData in LogService:GetLogHistory() do
	addMessage(messageData.message, messageData.messageType, false, messageData.timestamp)
end

Networking:SubscribeToTopic("console_messages", function(textType: Enum.MessageType, text: string, timestamp: number)
	addMessage(text, textType, true, timestamp)
end)

local Console = {
	MessageAdded = messageAddedSignal,
}

function Console.AddMessage(self, text: string, textType: Enum.MessageType, serverSided: boolean)
	assert(self == Console, "Expected ':' not '.' calling member function AddMessage")

	addMessage(text, textType, serverSided)
end

function Console.GetOutputLog(self)
	assert(self == Console, "Expected ':' not '.' calling member function GetOutputLog")

	local lines = {}

	local currentDate = os.date(`*t`)
	local currentDateFormatted =
		`{string.format("%02d", currentDate.hour)}:{string.format("%02d", currentDate.min)}:{string.format(
			"%02d",
			currentDate.sec
		)} {string.format("%02d", currentDate.day)}.{string.format("%02d", currentDate.month)}.{currentDate.year}`

	table.insert(lines, currentDateFormatted)
	table.insert(lines, `Generated by: {Players.LocalPlayer.Name}@{Players.LocalPlayer.DisplayName}`)
	table.insert(lines, `PlaceId: {game.PlaceId}`)
	table.insert(lines, `Version: {game.PlaceVersion}`)
	table.insert(lines, "")

	for _, messageData in messages do
		local milliseconds = tostring(math.floor((messageData.Timestamp - math.floor(messageData.Timestamp)) * 1000))
		local messageCount = messageData.Amount > 1 and ` [x{messageData.Amount}]` or ""

		table.insert(
			lines,
			`[{messageData.ServerSide and "SERVER" or "CLIENT"}][{os.date(`%X`, messageData.Timestamp)}.{milliseconds}][{messageData.ContentType.Name}] {messageData.Content}{messageCount}`
		)
	end

	return table.concat(lines, "\n")
end

return Console
