[package]
name = "dubit/fpscounter"
version = "0.1.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
license = "MIT"

description = "A super lightweight roblox FPS counter"

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.toml"]
