[package]
name = "dubit/tool-name"
version = "0.0.1"
realm = "shared"
registry = "https://github.com/Roblox-Devs-Dubit/wally-index"
licence = ""
authors = []

description = "Tool Description"

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.lock", "wally.toml"]

# [dev-dependencies]
# TestEz = "roblox/testez@0.4.1"
# ...

# [server-dependencies]
# ...

# [dependencies]
# ...