local CONSTANTS = {
	AUTHORIZED_GROUP_ID = 13711091,
	AUTHORIZED_GROUP_RANK = 200,

	MOBILE_GESTURE_DETECTION_AREA = 0.20,

	DROPDOWN_DISPLAY_ORDER = 1e+09,
	DEBUG_TOOL_DISPLAY_ORDER = 1e+09 - 1,
	WIDGET_DISPLAY_ORDER = 1e+09 - 2,

	NETWORK_TRAFFIC_REMOTE_NAME = "Mystery Remote Event",
	INJECTED_SCRIPTS_FOLDER_NAME = "[Debug Tools] Injected Scripts",

	NO_DEBUG_LAUNCH_DATA = "NODEBUG",
	IS_AUTHORIZED_ATTRIBUTE = "DEBUGTOOLS_ISAUTHORIZED",

	VERSION = "0.3.0",
}

table.freeze(CONSTANTS)

return CONSTANTS
