local CONSTANTS = {
	MOBILE_GESTURE_DETECTION_AREA = 0.20,

	DROPDOWN_DISPLAY_ORDER = 1e+09,
	DEBUG_TOOL_DISPLAY_ORDER = 1e+09 - 1,
	WIDGET_DISPLAY_ORDER = 1e+09 - 2,

	NETWORK_TRAFFIC_REMOTE_NAME = "*Mystery Remote Event*",

	IS_AUTHORIZED_ATTRIBUTE = "DEBUGTOOLS_ISAUTHORIZED",

	VERSION = "0.3.0",
}

table.freeze(CONSTANTS)

return CONSTANTS
