[package]
name = "dubit/notifications"
version = "0.1.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
licence = ""
authors = []

description = "Notification system that provides a managed queue for displaying notifications and popups with a limited lifespan."

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.lock", "wally.toml"]

[dev-dependencies]
TestEz = "roblox/testez@0.4.1"

[dependencies]
Signal = "sleitnick/signal@2.0.3"