[package]
name = "dubit/event-tracker"
version = "0.2.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
licence = ""
authors = []

description = "A proprietary Roblox global event library"

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.lock", "wally.toml"]

# [dev-dependencies]
# TestEz = "roblox/testez@0.4.1"

[dependencies]
Signal = "sleitnick/signal@2.x.x"