[package]
name = "dubit/anticheat"
version = "0.1.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
license = "MIT"

description = "designed to allow developers to implement a quick, standard anticheat into their experiences."

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
Runtime = "4x8matrix/runtime@1.0.0"
Signal = "sleitnick/signal@2.0.3"