[package]
name = "dubit/weaver-core"
version = "0.0.24"
realm = "shared"
registry = "https://github.com/Roblox-Devs-Dubit/wally-index"
licence = ""
authors = []

description = ""

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.lock", "wally.toml"]

# [dev-dependencies]
# TestEz = "roblox/testez@0.4.1"

[dependencies]
Promise = "evaera/promise@4.0.0"
Sift = "csqrl/sift@0.0.5"
Signal = "sleitnick/signal@1.5.0"