[package]
name = "dubit/environmenttool"
version = "0.1.0"
realm = "shared"
registry = "https://github.com/Roblox-Devs-Dubit/wally-index"

description = "An environment utility file for dubit projects"

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.toml"]

[dev-dependencies]
TestEz = "roblox/testez@0.4.1"
