[package]
name = "dubit/environmenttool"
version = "0.2.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
license = "MIT"

description = "An environment utility file for dubit projects"

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.toml"]

[dev-dependencies]
TestEz = "roblox/testez@0.4.1"
