[package]
name = "dubit/system"
version = "0.0.1"
realm = "shared"
registry = "https://github.com/Roblox-Devs-Dubit/wally-index"

description = "A prioritized Module Loader for Roblox."

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.toml"]
