[package]
name = "dubit/system"
version = "0.1.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
license = "MIT"

description = "A prioritized Module Loader for Roblox."

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.toml"]
